spring:
  application:
    name: Market Influences
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: ./data/lucene  
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb

# JDBC URL: jdbc:h2:mem:testdb
# User Name: sa
# Pasword: <leave this empty>

# Management
management:
  endpoints: 
    web:
      exposure:
        include: "*"
    enabled-by-default: true

logging:
  level: 
    org.springframework.web: WARN
    org.springframework.data: WARN

    